# Generated by Django 4.0.3 on 2023-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Busqueda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente_inicial',
            name='imagen',
        ),
    ]
