# Generated by Django 4.0.3 on 2023-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Busqueda', '0002_remove_fuente_inicial_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_inicial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='busquedas'),
        ),
    ]
