# Generated by Django 4.0.3 on 2023-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODO', models.TextField()),
                ('CONEXION', models.TextField()),
                ('DISTANCIA', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'grafo',
                'verbose_name_plural': 'grafos',
            },
        ),
    ]
