# Generated by Django 4.0.3 on 2023-08-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_grafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafo',
            name='DISTANCIA',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
