# Generated by Django 4.0.3 on 2023-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUNICIPIO', models.CharField(max_length=30)),
                ('DEPARTAMENTO', models.CharField(max_length=30)),
                ('LATITUD', models.FloatField(blank=True, null=True)),
                ('LONGITUD', models.FloatField(blank=True, null=True)),
                ('CAFE', models.FloatField(blank=True, null=True)),
                ('FAMILIAS_CAFE', models.FloatField(blank=True, null=True)),
                ('CAÑA', models.FloatField(blank=True, null=True)),
                ('FAMILIAS_CAÑA', models.FloatField(blank=True, null=True)),
                ('PINO_Y_EUCALIPTO', models.FloatField(blank=True, null=True)),
                ('FIQUE', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'produccion',
                'verbose_name_plural': 'producciones',
            },
        ),
    ]
