# Generated by Django 4.0.3 on 2023-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artificial_neural_networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extracion', models.TextField()),
                ('Municipio', models.TextField()),
                ('Zona', models.TextField()),
                ('Vereda', models.TextField()),
                ('Nombre_Fuente', models.TextField()),
                ('Observacion', models.TextField()),
                ('Observacion_2', models.TextField()),
                ('Dureza', models.FloatField(blank=True, null=True)),
                ('IP', models.FloatField(blank=True, null=True)),
                ('CBR', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'red_neuronal',
                'verbose_name_plural': 'redes_neuronales',
            },
        ),
    ]
